### ISSUE TITLE
Please add the ability to remember the user's choice for the "Hide when empty" parameter, so that after a system restart, the icon is not displayed in the tray

### ISSUE THREAD

**Issue by LisaJackson24-2** [BrandonXLF/compactor#1]
Thanks for the app, but please add the option to remember the user's choice, because currently option the "Hide when empty" is somewhat useless, because it only works in the current session, and after the system is restarted, the icon is displayed in the tray again. As an variant, it is possible to set the option permanently only if it is selected in the application when it is opened as an administrator. And to cancel the selection, if the user changes his mind, it will simply be necessary to reopen the program on behalf of the administrator, then the "Hide when empty" parameter will be reset and the icon will be displayed in the tray. Because I understand that if the user wants to cancel hiding, then the only option now is to delete something to send it to the trash, then the icon will appear in the tray and it will be possible to change the parameter.

**Comment by BrandonXLF** [comment]
I've released version 1.0.2 which addresses the first part of this issue, as the app was intended to function. I'll see if there's a good solution to the second problem. I don't think opening as admin is the best solution.

**Comment by LisaJackson24-2** [comment]
> I've released version 1.0.2 which addresses the first part of this issue, as the app was intended to function. I'll see if there's a good solution to the second problem. I don't think opening as admin is the best solution.

Oh, how fast. Very grateful.

Perhaps, really, running with administrator rights is not the best option. Another option, can add a key combination that is not used by the system for on/off. concealment.
